version: '3'

services:
    backend:
        build:
            context: ./backend
        image: dialup:backend
        tty: true
        volumes:
            - ./backend:/code
        ports:
            - "80:80"
        command: flask run -h 0.0.0.0 -p 80
        environment:
            FLASK_ENV: development
            FLASK_APP: index.py
            PYPPETEER_HOME: /pyppeteer
